### ISSUE TITLE
ServiceWorker errors: inactive tab, keepAlive

### ISSUE THREAD

**Issue by inomn** [AxaGuilDEv/react-oidc#862]
### Issue and Steps to Reproduce
Log in to your app;
Turn on 'Preserve log' setting of your js console;
Switch to another tab for some minutes;
Go back, see errors in console before you will be redirected to auth provider;

### Versions
Current latest;

### Screenshots
![Screenshot 2022-09-15 at 12 31 13](https://user-images.githubusercontent.com/6470994/190382042-b4249321-1afe-4151-ab7e-0787a2570192.png)

For better search posting here are errors:
```
initWorker.js:105          GET http://localhost:3000/OidcKeepAliveServiceWorker.json net::ERR_FAILED

bundle.js:23846          Uncaught (in promise) TypeError: Failed to fetch
    at keepAlive

OidcServiceWorker.js:262 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'access_token')
    at handleFetch (OidcServiceWorker.js:262:80)
```

**Comment by guillaume-chervet** [comment]
hi @inomn , thank you again for your issue :)

What does look like your oidc configuration?

Which OS and which browser do you use?

Fetch error are normal but I have to do it cleanner, but I'am interrested about the session lifetime problem.
How many time do you keep the tab inactive? does your computer turn in sleep mode ?

**Comment by inomn** [comment]
hi @guillaume-chervet thanks again for the answer :)

MacOS 12.4, Chrome 105.0.5195.125 (Official Build) (arm64)
Inactive between 10 and 30 minutes, with no sleep mode turning on or something.
Working all the time, using the same browser but other tabs.

Config file:
```
export const oidcConfiguration: OidcConfiguration = {
  client_id: 'frontend',
  authority: config.oidc.authority,
  redirect_uri: `${config.host}/authentication/callback`,
  scope: '',
  service_worker_relative_url:'/OidcServiceWorker.js',
  service_worker_only: false,
  authority_configuration: {
    authorization_endpoint: `${config.oidc.authority}/realms/test/protocol/openid-connect/auth`,
    token_endpoint: `${config.oidc.authority}/realms/test/protocol/openid-connect/token`,
    userinfo_endpoint: `${config.oidc.authority}/realms/test/protocol/openid-connect/userinfo`,
    end_session_endpoint: `${config.oidc.authority}/realms/test/protocol/openid-connect/logout`,
    revocation_endpoint: `${config.oidc.authority}/realms/test/protocol/openid-connect/revoke`,
    check_session_iframe: `${config.oidc.authority}/realms/test/protocol/openid-connect/login-status-iframe.html`,
    issuer: `${config.oidc.authority}/realms/test`,
  },
};
```

I still didn't get it, why Fetch error is normal? This whole bunch of errors will flood Sentry :) and overall looks not 'good' to have 'normal' errors for a such usual use case.

Btw one more issue I have: logout method (keycloak) fails.

```
http://localhost:8080/realms/test/protocol/openid-connect/logout?id_token_hint=undefined&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fbookings
```

Bad request: `Invalid parameter: id_token_hint`

**Comment by guillaume-chervet** [comment]
Hi @inomn, for for logout you need to add "openid" scope.

The client app trigger some fetch in order to keep alive the service worker alive the longer as possible (generally it can be many hours).
ServiceWorker increase a lot security but session lifetime is link to the serviceworker lifetime.

You can increase a lot the lifetime by using silent login: silent_redirect_uri: window.location.origin+'/authentication/silent-callback',
But now because browser start to block cookie tier, it is better to have a OIDC Server under the same domain than the application.

**Comment by guillaume-chervet** [comment]
One of the problem come from safari cookies tier blocked by default :
https://infi.nl/nieuws/spa-necromancy/
https://github.com/IdentityModel/oidc-client-js/issues/1074

I need a mac to reproduce it :/

**Comment by guillaume-chervet** [comment]
Silent signin is still an option if your oidc server share the same domain name. We do it at AXA.

For example:
App.axa.fr
Oidcserver.axa.fr

With an access token 2 minute lifetime, you may add "offline_access" scope to retrieve the refreh_token 😀

**Comment by mlsmaycon** [comment]
We also got the same error and we had to disable service workers for our project. 

Now we have a problem with the silent login being slow when the tab becomes active again and the API calls gets a expired token from the access token hook. 

@guillaume-chervet have you considered adding a promise function like getAccessTokenSilently from Auth0's sdk?

**Comment by guillaume-chervet** [comment]
Thank you again all for your feedbacks.
These error with the service worker is a normal behavior. I need to find a way to not display it. 

@mlsmaycon , do you use the fetch given by react oidc or do you inject access token yourself?

Do you have a video or something that can help me to understand the behavior?

I have done years of test with the silent signin, so i have implemented the best behavior i have found. I make all fetch with token wait for silent signin end when token are invalid before them to make a request when we are back to the tab. I have disable silent signin when the tab is inactive because it was failing. I think, It may still be enhanced.

I will give access to silentsignin methods though vanillaoidc methods. It is my next main task but it require some internal refactoring and clean up. I am pretty busy this month 😯

**Comment by mlsmaycon** [comment]
Hi @guillaume-chervet we are injecting the key [ourselves](https://github.com/netbirdio/dashboard/blob/main/src/views/Peers.tsx#L112). See the video with the problem:


https://user-images.githubusercontent.com/7747744/190903296-b9d638ef-82f9-4624-82d5-7caa59c8af86.mp4

**Comment by guillaume-chervet** [comment]
Thank you very much @mlsmaycon  for the video.

You may for that case wait the end of the synchronisation like done here => https://github.com/AxaGuilDEv/react-oidc/blob/bfd3784f626e03c3700a0058b27a913410580e8e/packages/react/src/oidc/FetchToken.tsx#L31

I have not found better solution by now :/

**Comment by tielushko** [comment]
> We also got the same error and we had to disable service workers for our project.
> 
> Now we have a problem with the silent login being slow when the tab becomes active again and the API calls gets a expired token from the access token hook.
> 
> @guillaume-chervet have you considered adding a promise function like getAccessTokenSilently from Auth0's sdk?

I second this issue very much! We use React Query in our project, and we allow for refetch on window focus. By the time we switch tabs, the token could get expired, and the renew request might take time to be satisfied before the app is usable again. Is there a way for background refetch of the token when the user is on a different tab/application? Where would you suggest using the synchronization code you have attached?  

Thank you for all your help!

**Comment by inomn** [comment]
Another related thing: how to set the logging level to errors only?
<img width="373" alt="Screenshot 2022-09-20 at 11 42 25" src="https://user-images.githubusercontent.com/6470994/191225055-debfc76f-1b3f-48ef-8a1a-b0b58c224e3e.png">


I set the token lifetime to days. Now after logging in I see this error:
```
OidcServiceWorker.js:263 Uncaught (in promise) DOMException: Failed to execute 'respondWith' on 'FetchEvent': The event handler is already finished.
    at handleFetch (http://localhost:3000/OidcServiceWorker.js:263:27)
```

**Comment by guillaume-chervet** [comment]
Hi @tielushko , you may use the fetch provided by useFetch hook given by react oidc. It is compatible with react query and will wait for tokens to be sync before making the request.

**Comment by guillaume-chervet** [comment]
Hi @inomn, the logs come from appauthjs used behind the seen. I have start to dig how to remove it but it is hidden. I am thinking more more to remove it and to ask oidc org to certify react oidc.

**Comment by guillaume-chervet** [comment]
Hi @tielushko ,

here how i use fetch=> https://github.com/AxaGuilDEv/ml-cli/blob/master/src/Ml.Cli.WebApp/ClientApp/src/Server/withCustomFetch.js

I inject fetch in my component as a dependency (to make code testable)

And i inject it by composition => https://github.com/AxaGuilDEv/ml-cli/blob/0ceccf0f6503437a83cd16a84aaf5497c20456a7/src/Ml.Cli.WebApp/ClientApp/src/Server/Dataset/Add/New/New.container.js#L201

**Comment by inomn** [comment]
Hi @guillaume-chervet , back to my initial message; So since it's errors, it will be captured by Sentry.
Same issue when you visiting inactive tab, first request can be without token \ with invalid token - error, and only then ServiceWorker will do his stuff. What's the recommended way to avoid ANY errors with using this lib? Thanks.

**Comment by guillaume-chervet** [comment]
Yes i think i can hide the error.

**Comment by guillaume-chervet** [comment]
I just published a new fix version 6.6.5. It seem to work. @inomn

**Comment by inomn** [comment]
Hi @guillaume-chervet thanks, I'm now on v6.6.6, looks like error was just replaced with log? 
But the fetch error is still there

![Screenshot 2022-09-23 at 10 21 54](https://user-images.githubusercontent.com/6470994/191920030-0b93121b-76a6-4a85-9354-cdf5674dfac4.png)


This happens after a really short inactivity time, like 2 minutes.
Here's a page refresh (not hard) after just 2 mins without activity

![Screenshot 2022-09-23 at 10 25 38](https://user-images.githubusercontent.com/6470994/191920611-553e7895-cb32-4d11-bb93-cb092feac846.png)

**Comment by guillaume-chervet** [comment]
yeah @inomn thank you, I am seraching how to fix this. it is a magic error :/

**Comment by beanovar** [comment]
Hi @guillaume-chervet - related to this conversation, our application has the need to continue polling the server even when the tab is in the background (a type of heartbeat). I've noticed the lib skips fetching a new token on token expiry if document.hidden is true. 
Is there a way to at least put an option in to allow the token to continually refresh in the background, even if the tab / page is not visible?  It would probably also fix the issues above where you come back to a tab and the token is now expired. Thanks.

**Comment by guillaume-chervet** [comment]
Hi @beanovar , It is a browser limitation. When a tab is inactive javascript have very few time to execute (that make fetch fail). I have to try to do it inside service worker to improve to lifetime.

**Comment by beanovar** [comment]
Hopefully we are talking about the same line, it's this one here: https://github.com/AxaGuilDEv/react-oidc/blob/bbb63160f255eba573b14e88453ad4d7fe24f259/packages/react/src/oidc/vanilla/oidc.ts#L946

My understanding is that timers are simply throttled for background tabs, but fetch requests should still work. Is it ok to provide an option to override this and allow it to try and continue fetching tokens when the document is hidden? I would be quite interested to see the behaviour of that...

**Comment by guillaume-chervet** [comment]
Yes i can make the behavior better for classic renew, but after a certain amount of time the browser does not give enough time to javascript to fetch. The silent sigin never work when the tab is inactive. It require to much operation.

**Comment by beanovar** [comment]
Thanks. I’m curious where you found that chrome will not give enough time for http fetches to successfully complete when the tab is in the background ? I’ve done digging and all I can find is that chrome will throttle your timers to only execute every second (even if they are scheduled to run more frequently) https://developer.chrome.com/blog/timer-throttling-in-chrome-88/

I can’t find anything that describes the amount of *time* you have to execute your code once the timer does trigger is limited ?

**Comment by guillaume-chervet** [comment]
I found it somewhere. As soon as find it again i will give it here. I will try to enhance the behavior to sync token the maximum as possible.

**Comment by chaimabenkaddour** [comment]
> Hi @guillaume-chervet - related to this conversation, our application has the need to continue polling the server even when the tab is in the background (a type of heartbeat). I've noticed the lib skips fetching a new token on token expiry if document.hidden is true. Is there a way to at least put an option in to allow the token to continually refresh in the background, even if the tab / page is not visible? It would probably also fix the issues above where you come back to a tab and the token is now expired. Thanks.

i have the same view i found a workaround that's work for me now :  `Object.defineProperty(document, "hidden", {
  configurable: true,
  get: function() { return true; }
});`  that's override document.hidden to be always true

**Comment by chaimabenkaddour** [comment]
> Hopefully we are talking about the same line, it's this one here:
> 
> https://github.com/AxaGuilDEv/react-oidc/blob/bbb63160f255eba573b14e88453ad4d7fe24f259/packages/react/src/oidc/vanilla/oidc.ts#L946
> 
> My understanding is that timers are simply throttled for background tabs, but fetch requests should still work. Is it ok to provide an option to override this and allow it to try and continue fetching tokens when the document is hidden? I would be quite interested to see the behaviour of that...

@beanovar  i have the same view i found a workaround that's work for me now : 

`
Object.defineProperty(document, "hidden", {
      configurable: true,
      get: function() { return false }
    });
`

that's override document.hidden to be always true

**Comment by guillaume-chervet** [comment]
Hi @beanovar @chaimabenkaddour 

Thank you very much for the information,  i will work on it tomorrow. 

Are you using serviceworker mode?

**Comment by chaimabenkaddour** [comment]
> Hi @beanovar @chaimabenkaddour
> 
> Thank you very much for the information, i will work on it tomorrow.
> 
> Are you using serviceworker mode?

Hi @guillaume-chervet no i'm not using the service worker and i'm using the v6.10.9

**Comment by MidoAhmed** [comment]
> Hopefully we are talking about the same line, it's this one here:
> 
> https://github.com/AxaGuilDEv/react-oidc/blob/bbb63160f255eba573b14e88453ad4d7fe24f259/packages/react/src/oidc/vanilla/oidc.ts#L946
> 
> My understanding is that timers are simply throttled for background tabs, but fetch requests should still work. Is it ok to provide an option to override this and allow it to try and continue fetching tokens when the document is hidden? I would be quite interested to see the behaviour of that...

Hi @guillaume-chervet 
same as the need of @beanovar out application use timers to fetch some data and should still working even on document hidden, so please do you see if there is a way to improve this behaviour 
 
browser: Chrome 
React 17.0.0
Axios 0.21.2
react-oidc 6.10.9 without service worker mode

**Comment by guillaume-chervet** [comment]
Hi @MidoAhmed , @chaimabenkaddour , @beanovar,
The version 6.10.16, now continue fetches refresh token in background.

It work also with mobile and laptop back after a sleep mode.

**Comment by MidoAhmed** [comment]
> fix(oidc): token not refreshed when hidden tab #902

@guillaume-chervet  thank you so mush for your reactivity

**Comment by beanovar** [comment]
Indeed thankyou @guillaume-chervet ! Look forward to trying it. Have you had any luck finding out what can be done about the failed keep alive fetch logs at all?

**Comment by guillaume-chervet** [comment]
Hi @beanovar , i do not find for the moment how to catch its error.

**Comment by dcopestake** [comment]
All the failed requests to the keep-alive endpoint mentioned as part of this should in theory be resolved as part of https://github.com/AxaGuilDEv/react-oidc/pull/967.
